server:
  port: 8000
spring:
  application:
    name: item
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.17.0.1:3306/cloud
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# feign 默认没有开启hystrix
feign:
  hystrix:
    enabled: true
